name: Setup Podman
description: Replace the Actions runners' ancient Podman with a usable version
runs:
  using: composite
  steps:
    - name: Setup Podman
      shell: bash
      run: |
        ubuntu_version="$(awk -F= '$1 ~ /DISTRIB_RELEASE/ {print $2}' /etc/lsb-release)"
        key_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key"
        sources_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}"

        echo "deb $sources_url/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
        curl -fsSL $key_url | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg >/dev/null

        sudo apt update
        sudo apt install podman
        sudo pip3 install podman-compose

        sudo podman container run --rm --privileged multiarch/qemu-user-static --reset -p yes
