version: "3.7"

volumes:
  cache:
  data:
  database:

services:
  web:
    image: ghcr.io/lukecarrier/moodle-nginx:latest
    ports:
      - 8080:80
    depends_on:
      - app
    security_opt:
      - label=disable
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached

  app:
    image: ghcr.io/lukecarrier/moodle-php-fpm-8.0:latest
    depends_on:
      - database
    env_file:
      - .env
    security_opt:
      - label=disable
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - type: volume
        source: data
        target: /data
        consistency: delegated
      - type: bind
        source: ./_docker/data/app/profiler
        target: /data/profiler

  #cache:
  #  image: redis
  #  ports:
  #    - 6379:6379
  #  volumes:
  #    - type: volume
  #      source: cache
  #      target: /var/lib/redis
  #      consistency: delegated

  # MySQL
  #database:
  #  image: mysql:8.2
  #  ports:
  #    - 13306:3306
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 2GB
  #      reservations:
  #        memory: 1GB
  #  volumes:
  #    - type: volume
  #      source: database
  #      target: /var/lib/mysql
  #      consistency: delegated

  # Oracle
  #database:
  #  imag e: moodlehq/moodle-db-oracle-r2:21
  #  port s:
  #    -  11521:1521
  #  depl oy:
  #    re sources:
  #       limits:
  #         memory: 2GB
  #       reservations:
  #         memory: 2GB
  #  volu mes:
  #    -  type: volume
  #       source: database
  #       target: /opt/oracle/oradata
  #      consistency: delegated

  # PostgreSQL
  #database:
  #  image: postgres:16.1
  #  ports:
  #    - 15432:5432
  #  env_file:
  #    - .env
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 1GB
  #      reservations:
  #        memory: 512MB
  #  volumes:
  #    - type: volume
  #      source: database
  #      target: /var/lib/postgresql/data
  #      consistency: delegated

  # SQL Server
  #database:
  #  image: ghcr.io/lukecarrier/moodle-sql-server:latest
  #  ports:
  #    - 11433:1433
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 4GB
  #      reservations:
  #        memory: 2GB
  #  volumes:
  #    - type: volume
  #      source: database
  #      target: /var/opt/mssql/data
  #      consistency: delegated

  #antivirus:
  #  image: mailu/clamav:latest
  #  ports:
  #    - 3310:3310

  #selenium-hub:
  #  image: selenium/hub
  #  ports:
  #    - 4444:4444

  #selenium-node-chrome:
  #  image: selenium/node-chrome
  #  environment:
  #    - HUB_PORT_4444_TCP_ADDR=selenium-hub
  #    - HUB_PORT_4444_TCP_PORT=4444
  #  depends_on:
  #    - selenium-hub
  #  ports:
  #    - 5901:5900

  #selenium-node-firefox:
  #  image: selenium/node-firefox
  #  environment:
  #    - HUB_PORT_4444_TCP_ADDR=selenium-hub
  #    - HUB_PORT_4444_TCP_PORT=4444
  #  depends_on:
  #    - selenium-hub
  #  ports:
  #    - 5902:5900
