name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build_images:
    strategy:
      matrix:
        image:
          - nginx
          - php-fpm-7.0
          - php-fpm-7.2
          - php-fpm-7.4
          - php-fpm-8.0
          - php-fpm-8.2
          - sql-server
        target_arch: [amd64, arm64]
        exclude:
          - image: sql-server
            target_arch: arm64

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.export_version.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Podman
        uses: ./.github/actions/setup-podman
      - name: Authenticate with registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Export version
        id: export_version
        run: |
          set -eu
          revision="${{ github.event.pull_request.head.sha }}"
          echo "image_tag=git-$revision" >>"$GITHUB_ENV"
          echo "image_tag=git-$revision" >>"$GITHUB_OUTPUT"
      - name: Build and push image
        run: |
          target="${{ matrix.image }}-${{ matrix.target_arch }}"
          make "build-${target}"
          make "push-${target}"

  assemble_manifests:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    needs: build_images

    strategy:
      matrix:
        include:
          - image: nginx
            target_arch: amd64:arm64
          - image: php-fpm-7.0
            target_arch: amd64:arm64
          - image: php-fpm-dev-7.0
            target_arch: amd64:arm64
          - image: php-fpm-7.2
            target_arch: amd64:arm64
          - image: php-fpm-dev-7.2
            target_arch: amd64:arm64
          - image: php-fpm-7.4
            target_arch: amd64:arm64
          - image: php-fpm-dev-7.4
            target_arch: amd64:arm64
          - image: php-fpm-8.0
            target_arch: amd64:arm64
          - image: php-fpm-dev-8.0
            target_arch: amd64:arm64
          - image: php-fpm-8.2
            target_arch: amd64:arm64
          - image: php-fpm-dev-8.2
            target_arch: amd64:arm64
          - image: sql-server
            target_arch: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Podman
        uses: ./.github/actions/setup-podman
      - name: Authenticate with registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Assemble and push manifest
        run: |
          set -eux -o pipefail

          local_manifest="moodle-${{ matrix.image }}:${{ needs.build_images.outputs.image_tag }}"
          remote_manifest="ghcr.io/lukecarrier/${local_manifest}"
          podman manifest create "$local_manifest"

          IFS=: read -r -a target_arch <<<"${{ matrix.target_arch }}"
          for arch in "${target_arch[@]}"; do
            image="ghcr.io/lukecarrier/moodle-${{ matrix.image }}:${{ needs.build_images.outputs.image_tag }}-$arch"
            podman image pull "$image"
            podman manifest add "$local_manifest" "$image"
          done

          podman manifest push --all "$local_manifest" "$remote_manifest"
